# Numpy practice codes


In [4]:
import numpy as np
np.__version__

'1.13.1'

In [8]:
my_list = [3,4,5,6]
array = np.array(my_list)
array

array([3, 4, 5, 6])

In [9]:
print(my_list * 3)
print(array * 3)

[3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6]
[ 9 12 15 18]


In [10]:
tuple = (3, 4.5, 2+5j)
array = np.array(tuple)
array

array([ 3.0+0.j,  4.5+0.j,  2.0+5.j])

# Array Creationg using arange function

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(15,20)

array([15, 16, 17, 18, 19])

In [15]:
len(np.arange(20,30))

10

In [18]:
np.arange(15,35).size

20

In [19]:
np.arange(4,40,5)

array([ 4,  9, 14, 19, 24, 29, 34, 39])

# Numpy functions linspace(), zeros(), ones()

In [23]:
#start and stop parameter mendatory for linespace . Linspace is closed interval but arange is not.
np.linspace(5,25,4)

array([  5.        ,  11.66666667,  18.33333333,  25.        ])

In [27]:
space = np.linspace(5,40,9, retstep=True)
space

(array([  5.   ,   9.375,  13.75 ,  18.125,  22.5  ,  26.875,  31.25 ,
         35.625,  40.   ]), 4.375)

In [28]:
space[1]

4.375

In [32]:
np.zeros(8)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [33]:
np.zeros(8, dtype="int64")

array([0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

# Multidimensional arrays


In [37]:
np.zeros((4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [38]:
np.ones((5,4,3))  #

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])